### ISSUE TITLE
Add Authentication 

### ISSUE THREAD

**Issue by vikash28-cloud** [vikash28-cloud/Password-Manager#3]
Add Authentication to this site -
first user should enter login id and password then he/she can see their passwords

**Comment by Sushilgavit** [comment]
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

public class AuthenticationSystem {
    private Map<String, String> userCredentials;

    public AuthenticationSystem() {
        user = new HashMap<>();
        // U can add information from the db
        user.put("userOne", "1234");
        user.put("userTwo", "5678");
        
    }

    public boolean authenticate(String username, String password) {
        // Check if the username exists in the map and if the password matches
        return user.containsKey(username) && user.get(username).equals(password);
    }

    public static void main(String[] args) {
        AuthenticationSystem authSystem = new AuthenticationSystem();
        Scanner scanner = new Scanner(System.in);

        System.out.println("Welcome");

        while (true) {
            System.out.print("Enter your username: ");
            String username = scanner.nextLine();
            System.out.print("Enter your password: ");
            String password = scanner.nextLine();

            if (authSystem.authenticate(username, password)) {
                System.out.println("Auth successful.");
                // You can redirect the user to the site or perform other actions here
                break; // Exit the loop once authenticated
            } else {
                System.out.println("Authentication failed. Please try again.");
            }
        }

     
    }
}

**Comment by vikash28-cloud** [comment]
thanks for contribute
